[[WolframAppDiscovery]]
arch = "aarch64"
git-tree-sha1 = "a63ff3c707ad9a2a4de3d2c49e3a00cac4a2fc78"
os = "macos"

    [[WolframAppDiscovery.download]]
    sha256 = "f4c1cf4f97b4e6f91ebf195c42d658d38ed31e8f68890cbe62e5c4523056f56b"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.aarch64-apple-darwin.tar.gz"
[[WolframAppDiscovery]]
arch = "aarch64"
git-tree-sha1 = "6df3d74d56a4d5d036ae5db890fdb0ab75f1f844"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "b93c4d46f279e39cf7b98f08ad61787eed8de337eed6a0a9ca73eeb2a2221824"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.aarch64-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "aarch64"
git-tree-sha1 = "cd80abcf8b9ecb2e093a31e2d9db5e9c0c1b468a"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "358e73f4f7ad194a985ad55f671c45383aaa6d8fac25512b7438c83b4c9a666f"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.aarch64-linux-musl.tar.gz"
[[WolframAppDiscovery]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb251dcf2a606130fef146df79a98e9d3f3ff258"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "621068a4c00fd0a1cca1fdd07956729c15545e389afcb4a5190d2d3962d78210"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.armv6l-linux-gnueabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97869c6f581bf433dc553444f1ddcb4235e9ac91"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "1b3bcf78c2b3c3e01150ef6046c8915bc7aff5937dd49124ec2f827e122e5a38"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.armv6l-linux-musleabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d10c5d3e50f7d50d6464d3eeaadcc210df419734"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "62d0def8480cf7a1ee7332e4416ee76e1bcd21de8b1d0da5715852dc1ad27ca8"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.armv7l-linux-gnueabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd2082b7085ae93f40cdeaba3c265f9c29e41450"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "bb2a23e405d976a5e6bb263e4c9a31a2b4e62807e2d329346774f92a8ebaadf9"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.armv7l-linux-musleabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "i686"
git-tree-sha1 = "a3bff2d95a846f6f15360303797d2088c62c4d89"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "4b97e2f522ffef83fb821f07b818799bf10d7ab724f31aad45435c0ba6dc7343"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.i686-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "i686"
git-tree-sha1 = "087fbdbc1c5b8356fbaa5f54f4ef8cced737e3ef"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "70021b5b5fec24893f23cf69c3ff8eb450b6dea05b71a42c2391ff8b2a2789ae"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.i686-linux-musl.tar.gz"
[[WolframAppDiscovery]]
arch = "powerpc64le"
git-tree-sha1 = "27177dea9e6e9061b6a10085c902f9baef4ddd2e"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "eca85bff4ce798ee6b0594e3ecd2b8718f34e198ac623e52b6f571da67468be2"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.powerpc64le-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "dce493b9adc6f027f8d10e1ab608cada561b7ddc"
os = "macos"

    [[WolframAppDiscovery.download]]
    sha256 = "9d89670d941c8e61693bbeae6b3e849deb3dc37f3c24551e502a0b8d696c70f5"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.x86_64-apple-darwin.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "04d9dc941b3c6703606fc0b8ca21611dc7523a6c"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "3e1e888ad923a9c6b53daf814329e2a00a51045ba003eebd1b088d83c0153142"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.x86_64-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "e1ac6b10190fa0a553e0d695d6a73743de1041d7"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "07f4cc1f6d894b55f1375b02f2d5b10b004e3ac6f92d7975ba8fd5b263da4782"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.x86_64-linux-musl.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "68e5d0746e428b62e3e98ae8f556453cefc2434f"
os = "freebsd"

    [[WolframAppDiscovery.download]]
    sha256 = "8550c36ea211ab66fa5736ec102950e63af387168596c69083187befdb343634"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.x86_64-unknown-freebsd.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "bb18f7203f8369c28594422366cb29761cff0340"
os = "windows"

    [[WolframAppDiscovery.download]]
    sha256 = "f15447b2cfc154441db7d25055822959f1c48254901f723510ce2cf8ef4ca9a0"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.3+0/WolframAppDiscovery.v0.4.3.x86_64-w64-mingw32.tar.gz"
