[[WolframAppDiscovery]]
arch = "aarch64"
git-tree-sha1 = "eae126d358288f08e831f77c6a04b6eb309c231a"
os = "macos"

    [[WolframAppDiscovery.download]]
    sha256 = "fde36c5a9a4960794434d3da9d0044592d8450f38fd0b669c557195c52e73bf3"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.aarch64-apple-darwin.tar.gz"
[[WolframAppDiscovery]]
arch = "aarch64"
git-tree-sha1 = "c72095f35632962b7880f08828c7b9ded5f3fae1"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "6682d5b7476114c77462b789624a85efe81c3aeee7b2d46a28feb992d60d64d7"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.aarch64-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "aarch64"
git-tree-sha1 = "e863ccc7e36fa9e944b2201c9acd95ff88a6b0f8"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "fd167c4eac6d0cdceb5d42967272170e67e78d245df25ec1acc0243288d15d0f"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.aarch64-linux-musl.tar.gz"
[[WolframAppDiscovery]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99ed22b994d2c4643fa506549410e4dbe4e17d49"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "09395db368a2c22b37357a2a5a347f4b59410ebc58aa9623d3421b21bf48ea54"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.armv6l-linux-gnueabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73256430a9c260e2aa0be02feceae4ae64179b3b"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "bf4ec4d5ec3d457a4a60a5ae5f315206006f0d99266f89973a28d779da2d8480"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.armv6l-linux-musleabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f166028c722c59aedf5e4233d34459f0725ca3dc"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "6b339af3b50e8ed2b85678433ae58f3744e96ed62109abfd71e26e17fec25a7f"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.armv7l-linux-gnueabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd2ac6d726dcb4ac7ebccf08ae54fce89cbfa68d"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "9ab39a3ca6a2cc767defedc6329c1eac75f33995487f2988a9e081bc213910c3"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.armv7l-linux-musleabihf.tar.gz"
[[WolframAppDiscovery]]
arch = "i686"
git-tree-sha1 = "a2b1a4f82dcbd857db8efc69ec56090e5511119f"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "175a856af2cbbe040c47f45be5c51d9c8729e5adffdf3d73e67d314c7fad7f38"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.i686-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "i686"
git-tree-sha1 = "771982ea39f792dc52dca2c4c433821f24f06316"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "544bf2fc131a3b82057cfa6735ccfa132e72e241a54b0d6a1f4e81b579e9a3ee"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.i686-linux-musl.tar.gz"
[[WolframAppDiscovery]]
arch = "powerpc64le"
git-tree-sha1 = "4f599e6bb3866dc43f0b0737916b2a0dd0d8fc83"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "2ba231960efec186a13141f64a0d7decbabbb33074dbeb9bfd4e5a13fd0db789"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.powerpc64le-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "45a2986dc883cdd8c5a6afa469f1ecfc32417b9e"
os = "macos"

    [[WolframAppDiscovery.download]]
    sha256 = "ab0e73d98013a6e42f804bcef3fb8b78441a0a76e32443ce68ba5ff6a6ff9cdd"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.x86_64-apple-darwin.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "c19816da93459263de3cf347065edeee8594bf16"
libc = "glibc"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "620bb92020a93e7aa35369d32e9997f2d91cb325e4d401558666b1e920c6da14"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.x86_64-linux-gnu.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "77712365a7887394a516ad9e0e10a70dcc81cb76"
libc = "musl"
os = "linux"

    [[WolframAppDiscovery.download]]
    sha256 = "82f76287c765e0cb230fed01dbe5e03ac375a874bc32e899896303f66bc747ea"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.x86_64-linux-musl.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "20570f3f8f9e966078d882984dc21b00c82e17b4"
os = "freebsd"

    [[WolframAppDiscovery.download]]
    sha256 = "4314d24f705152cba0efb4c6362e8f98f79759d0c94111a60d4f9a779376d5f3"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.x86_64-unknown-freebsd.tar.gz"
[[WolframAppDiscovery]]
arch = "x86_64"
git-tree-sha1 = "74e0c1ba6bfc94c251fa2c6927358d7af725979c"
os = "windows"

    [[WolframAppDiscovery.download]]
    sha256 = "704f01dd51b85424296546a917899623665054f7e18ed8dc78085146a8cdcc27"
    url = "https://github.com/JuliaBinaryWrappers/WolframAppDiscovery_jll.jl/releases/download/WolframAppDiscovery-v0.4.4+0/WolframAppDiscovery.v0.4.4.x86_64-w64-mingw32.tar.gz"
